/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BlogStatus = "archived" | "draft" | "published";

export type DayOfWeek = "friday" | "monday" | "saturday" | "sunday" | "thursday" | "tuesday" | "wednesday";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface BlogCategory {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface Blog {
  authorId: number | null;
  categoryId: number | null;
  content: string;
  coverFileId: number | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  seoDescription: string | null;
  seoKeywords: string | null;
  seoTitle: string | null;
  slug: string;
  status: Generated<BlogStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface ContactEntry {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  message: string;
  name: string;
  phone: string;
  updatedAt: Generated<Timestamp>;
}

export interface Department {
  createdAt: Generated<Timestamp>;
  headerDescription: string;
  icon: string;
  id: Generated<number>;
  name: string;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface DepartmentSectionCard {
  createdAt: Generated<Timestamp>;
  description: string;
  displayOrder: number;
  icon: string;
  id: Generated<number>;
  sectionId: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface DepartmentSection {
  createdAt: Generated<Timestamp>;
  departmentId: number;
  description: string;
  displayOrder: number;
  id: Generated<number>;
  label: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Doctor {
  createdAt: Generated<Timestamp>;
  departmentId: number | null;
  description: string;
  email: string | null;
  id: Generated<number>;
  location: string | null;
  name: string;
  phoneNumber: string | null;
  photoFileId: number | null;
  role: string;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface DoctorsAchievement {
  createdAt: Generated<Timestamp>;
  displayOrder: number;
  doctorId: number;
  id: Generated<number>;
  title: string;
  updatedAt: Generated<Timestamp>;
  year: number;
}

export interface DoctorsAppointmentHour {
  createdAt: Generated<Timestamp>;
  day: DayOfWeek;
  displayOrder: number;
  doctorId: number;
  id: Generated<number>;
  timeEnd: string;
  timeStart: string;
  updatedAt: Generated<Timestamp>;
}

export interface DoctorsEducation {
  createdAt: Generated<Timestamp>;
  degree: string;
  displayOrder: number;
  doctorId: number;
  id: Generated<number>;
  institution: string;
  updatedAt: Generated<Timestamp>;
  yearOfCompletion: number;
}

export interface DoctorsExperience {
  createdAt: Generated<Timestamp>;
  displayOrder: number;
  doctorId: number;
  id: Generated<number>;
  role: string;
  shortDescription: string;
  updatedAt: Generated<Timestamp>;
}

export interface Email {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  isPrimary: Generated<boolean>;
  isVerified: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Gallery {
  authorId: number | null;
  content: string;
  coverFileId: number | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  seoDescription: string | null;
  seoKeywords: string | null;
  seoTitle: string | null;
  slug: string;
  status: Generated<BlogStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface GalleryImage {
  caption: string;
  displayOrder: number;
  fileId: number;
  galleryId: number;
}

export interface PinnedNotice {
  createdAt: Generated<Timestamp>;
  fileId: number | null;
  id: Generated<number>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Session {
  city: string | null;
  country: Generated<string>;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ip: string;
  region: string | null;
  updatedAt: Generated<Timestamp>;
  userAgent: string;
  userId: number;
}

export interface UploadedFile {
  fileType: string;
  id: Generated<number>;
  name: string;
  uploadedAt: Generated<Timestamp>;
  url: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  password: string;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  blogCategories: BlogCategory;
  blogs: Blog;
  contactEntries: ContactEntry;
  departments: Department;
  departmentSectionCards: DepartmentSectionCard;
  departmentSections: DepartmentSection;
  doctors: Doctor;
  doctorsAchievements: DoctorsAchievement;
  doctorsAppointmentHours: DoctorsAppointmentHour;
  doctorsEducation: DoctorsEducation;
  doctorsExperiences: DoctorsExperience;
  emails: Email;
  galleries: Gallery;
  galleryImages: GalleryImage;
  pinnedNotices: PinnedNotice;
  sessions: Session;
  uploadedFiles: UploadedFile;
  users: User;
}
